[FeatureSettings]
kobo_dropbox_link_account_enabled=True
kobo_googledrive_link_account_enabled=True

[OneStoreServices]
api_endpoint=http://your-server-ip:8083/kobo/your-unique-key

[Reading]
DictionaryQuickLookup=true
distinctMarginIncrements=true